# +--- Anaconda Python configuration --------------------------------+

# Conda Initialization
#   The following is autogenerated from 'conda init'
#   and serves to add various commands to conda such as 'activate'
#   see the followin link for detailed explanation: https://stackoverflow.com/a/69024715
__conda_setup="$('/Users/matthewanderson/.local/share/pyenv/versions/miniconda3-latest/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/matthewanderson/.local/share/pyenv/versions/miniconda3-latest/etc/profile.d/conda.sh" ]; then
        . "/Users/matthewanderson/.local/share/pyenv/versions/miniconda3-latest/etc/profile.d/conda.sh"
    else
        export PATH="/Users/matthewanderson/.local/share/pyenv/versions/miniconda3-latest/bin:$PATH"
    fi
fi
unset __conda_setup

